# Generated by Django 4.1.6 on 2023-02-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("img", models.ImageField(upload_to="product/")),
                ("description", models.TextField(max_length=200)),
            ],
        ),
    ]
